
  version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: login_db_9w8c_user
      POSTGRES_PASSWORD: 1HBhd8lEmnTXnX9L90GRTrzP5hbZhGNL
      POSTGRES_DB: login_db_9w8c
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot_app
    depends_on:
      - db
    environment:
      - DATABASE_URL=jdbc:postgresql://dpg-cvdd7grtq21c73abpe90-a:5432/login_db_9w8c
      - DATABASE_USER=login_db_9w8c_user
      - DATABASE_PASSWORD=1HBhd8lEmnTXnX9L90GRTrzP5hbZhGNL
    ports:
      - "8080:8080"

volumes:
  postgres_data:


