version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: login_db_9w8c_user
      POSTGRES_PASSWORD: 1HBhd8lEmnTXnX9L90GRTrzP5hbZhGNL
      POSTGRES_DB: login_db_9w8c
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

